//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace intprogvize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki
    {
        public string yetkiId { get; set; }
        public string yetki1 { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Ogretmen Ogretmen { get; set; }
    }
}
